name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
          chmod 400 deploy_key.pem
          echo "Starting SSH connection"
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts  # Ensure the known_hosts file exists
          ssh-keyscan -H 51.20.52.140 >> ~/.ssh/known_hosts
          ssh -v -i ./deploy_key.pem ubuntu@51.20.52.140 "echo Hello from the server"
          
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Theme Assets
        run: npm run build

      # - name: Build Theme Assets
      #   run: |
      #     # Navigate to your theme directory
      #     cd /var/www/html/melvinmagro.online/wp-content/themes/your-theme-name

        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}

