name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Deploy to Server
      #   run: |
      #     echo "Deploying to server using GitHub PAT"
          
      - name: Debug Logging
        run: |
          ls -la /var/www/html
          echo "GitHub Actions runner user: $USER"
          
          # Add any additional deployment steps as needed.

        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}

