name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Deploying to server using GitHub PAT"
          
          # Example: Use the PAT to clone or fetch your code on the server
          git clone https://github.com/MelvinMagro/wis.git /var/www/html/melvinmagro.online
          
          # Add any additional deployment steps as needed.

        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}

